#include "/home/wpc/bin/macros.h"
#include "/home/wpc/bin/systemC.asm"
#include "technologiesC.asm"
#include "harmonyC.asm"
#include "csvfilereaderC.asm"


void Pmain(/* original paramtype was [] paramspace = 0*/int * framepointer  );
#define spaceforPmainl194  0
char PmainBaset[spaceforPmainl194];
/* since we can not be sure which direction mem allocated by c we double allocate in both directions */
char PmainBase[ spaceforPmainl194 ];

//procedure Pmain  generated by code generator class ilcg.tree.CCG
void Pmain(/* original paramtype was [] paramspace = 0*/int * framepointer  )
{
// entering a procedure at lexical level 0
	char locals[24];
	int    *ESP;
	register int r0,r1,r2; 
	int r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15;
	float F0,F1,F2,F3;
	double D0,D1,D2,D3;
	ESP=((int*)&locals[16]); 
/* we emulate the enter instruction by storing the old EBP in the frame */
	ESP[0]=(int)framepointer;
/* we copy over the C params into the image of an Intel Pascal frame */
//paramtype 
	r2 =(&locals[16]); 
 unit$system();
 unit$technologies();
 unit$harmony();
 unit$csvfilereader();
static int Pmainready=0;
	if(Pmainready==1)goto Pmainl194exit;
Pmainready=1;
 label16667a3537b1e10:
Pmainl194exit:;
}
//invocations per line output =0.22580645161290322
//invocations per source statement =3.5
//assembler lines per source statement =16.5




#define z346g .data
